In [8]:
import torch
import numpy as np
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [3]:
randint = torch.randint(-100, 100,(6,))
randint

tensor([-38,  23, -35,  -3,  77, -86])

In [6]:
tensor = torch.tensor([[0.1, 1.2], [2.2,3.1], [4.9, 5.2]])
tensor

tensor([[0.1000, 1.2000],
        [2.2000, 3.1000],
        [4.9000, 5.2000]])

In [8]:
zeros = torch.zeros(2,3)
zeros

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
ones = torch.ones(3,4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [12]:
input = torch.empty(2,3)
input

tensor([[5.3601e-08, 5.3410e-08, 1.0802e-05],
        [5.4167e-05, 8.3448e-10, 5.4407e-05]])

In [13]:
arange = torch.arange(5)
arange

tensor([0, 1, 2, 3, 4])

In [16]:
linespace = torch.linspace(3,10,steps=20)
linespace

tensor([ 3.0000,  3.3684,  3.7368,  4.1053,  4.4737,  4.8421,  5.2105,  5.5789,
         5.9474,  6.3158,  6.6842,  7.0526,  7.4211,  7.7895,  8.1579,  8.5263,
         8.8947,  9.2632,  9.6316, 10.0000])

In [19]:
logspace = torch.logspace(start=-10, end =10, steps = 4)
logspace

tensor([1.0000e-10, 4.6416e-04, 2.1544e+03, 1.0000e+10])

In [20]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [22]:
a = torch.empty((2,3), dtype=torch.int64)
empty_like = torch.empty_like(a)
empty_like, empty_like.dtype

(tensor([[29555319237705820, 12948244072038514, 32651616996819049],
         [25896170311057512, 28710924373327984, 26740556586287209]]),
 torch.int64)

In [3]:
# GPU vs CPU
import time
start_time = time.time()

zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time-start_time
print(f"Elapsed time = {elapsed_time:.5f}")

Elapsed time = 0.00099


In [5]:
torch_rand1 = torch.rand(10000, 10000).to(device)
torch_rand2 = torch.rand(10000, 10000).to(device)

numpy_rand1 = torch.rand(10000, 10000)
numpy_rand2 = torch.rand(10000, 10000)

In [6]:
%%timeit
rand = torch_rand1.matmul(torch_rand2)

The slowest run took 4.29 times longer than the fastest. This could mean that an intermediate result is being cached.
38.3 µs ± 25.7 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
%%timeit
res = np.multiply(numpy_rand1, numpy_rand2)

183 ms ± 9.34 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
